### ISSUE TITLE
Don't change wave "design" when the color is changed

### ISSUE THREAD

**Issue by Nojze** [anup-a/svgwave#15]
There may be moments where the user (i.e. me) wants to test the same wave "design" but with different colors, right now, the "design" of the wave changes every time I change the color. 
See example [here](https://gyazo.com/bb4bb198c71b7aa62953c33c881426c8)

Would be nice If the wave "design" stayed the same, even when I change the color of the wave 😃

**Comment by anup-a** [comment]
@Nojze will be fixing this very soon. Thanks for letting me know
