### ISSUE TITLE
[React] [SVG] Add a slider to adjust different vertical between waves 🌊

### ISSUE THREAD

**Issue by anup-a** [anup-a/svgwave#2]
As of now there is default height for each layer of waves ( an defined in constants), the task is to add a slider input to manually  change the vertical distance between the waves.

- Fit slider in the customization Bar ( a suggestion to fit it vertically besides other sliders )
- Remove height array from constants and change it dynamically

**Comment by yashsk98** [comment]
Hi @anup-a, 
I am relatively new to React, but this looks interesting and fun. Can I give this a whirl?

**Comment by anup-a** [comment]
@yashsk98  No problem. go ahead.
Feel free to ask if you have any questions.

**Comment by Remakh** [comment]
Can anyone give this a go, or is someone assigned to/ could I assign myself?

**Comment by yashsk98** [comment]
Hi @Remakh, 
Is it alright if I try this till Sunday? If not, you can do it. Looks better than to compete and end up doing overlapping work right? Does that sound ok @anup-a ?

**Comment by anup-a** [comment]
@yashsk98 thats ok for me.

**Comment by Remakh** [comment]
@yashsk98 I already finished it lol
