### ISSUE TITLE
[React] Use localstorage to store current theme settings

### ISSUE THREAD

**Issue by anup-a** [anup-a/svgwave#3]
- Default dark mode should be fetched from local storage (if present)
- Change the theme value in local storage (if changed)
- Or use system setting ( to make default light/dark mode)

**Comment by yencolon** [comment]
Hey, I think I can help you with this!

**Comment by anup-a** [comment]
Sure, go ahead ...
try not to use any library 👍

**Comment by yencolon** [comment]
Sure, assign this to me

**Comment by anup-a** [comment]
@yencolon great work!👍
Give us ⭐ on the repo.
