### ISSUE TITLE
Add a state management (like zustand) for global state

### ISSUE THREAD

**Issue by anup-a** [anup-a/svgwave#33]
Few settings such as dark mode & wave defaults would be much better if there is global state manager.
- Zustand is preferable due to its very minimal boilerplate code.

**Comment by imadatyatalah** [comment]
Can I work on this issue?

**Comment by anup-a** [comment]
hi @imadatyatalah 

yeah sure. Assigning it to you. feel free to ask any questions.

**Comment by imadatyatalah** [comment]
Thank you!

I want to ask if I should just setup Zustand or use it in the project(like get the current color-mode?..)?

**Comment by anup-a** [comment]
Yup thats it. 

Excpectations --
There should be a global store with zustand, and that should contain at least color theme for now.  And all the theme logic should use zustand store instead of props .

Future scope -- We will plan to migrate other settings to this store.
