### ISSUE TITLE
React: Add github star button in Navbar

### ISSUE THREAD

**Issue by anup-a** [anup-a/svgwave#35]
Add github start button in the UI, with link to this repo.

Button styling should be as mentioned here - 
https://buttons.github.io/

**Comment by zivkaziv** [comment]
Can I take this issue?

**Comment by zivkaziv** [comment]
Where do we want to set this button
Do we want this type of button?
<img width="195" alt="Screen Shot 2021-10-02 at 15 19 12" src="https://user-images.githubusercontent.com/9402714/135715823-e7ebef65-15eb-48f0-8f79-5a007a7fb024.png">
?

**Comment by anup-a** [comment]
> Where do we want to set this button Do we want this type of button? <img alt="Screen Shot 2021-10-02 at 15 19 12" width="195" src="https://user-images.githubusercontent.com/9402714/135715823-e7ebef65-15eb-48f0-8f79-5a007a7fb024.png"> ?

@zivkaziv  Yeah Exactly.

I think this should be in the Navbar.

Cool. Assigning you the issue. Feel free to ask any questions.

**Comment by zivkaziv** [comment]
Thank you:)
Do you want to replace the current github icon? or to add it next to it?
I'll add support for darkmode as well

**Comment by Nikhil27b** [comment]
#40  Added

**Comment by zivkaziv** [comment]
Created a PR for it- https://github.com/anup-a/svgwave/pull/41

**Comment by anup-a** [comment]
> Created a PR for it- #41

Thanks for the PR. Just a suggestion - can you remove package-lock and yarn.lock from your commit?

**Comment by zivkaziv** [comment]
I remove package-lock, but yarn.lock somehow still there... I'll try to submit it again

**Comment by zivkaziv** [comment]
Ok, I created another PR instead - https://github.com/anup-a/svgwave/pull/44 without those files

**Comment by anup-a** [comment]
> I remove package-lock, but yarn.lock somehow still there... I'll try to submit it again

@zivkaziv Thanks for the PR.

**Comment by zivkaziv** [comment]
Any chance you can add hacktoberfest-accepted to the PR?

**Comment by anup-a** [comment]
> Any chance you can add hacktoberfest-accepted label to the PR?

Hey its already added. Let me know if still didn't appear on your Hacktoberfest profile

**Comment by zivkaziv** [comment]
Thank you:)
I see it now
