### ISSUE TITLE
React: Add angle option in gradient color picker for waves.

### ISSUE THREAD

**Issue by anup-a** [anup-a/svgwave#37]
Right now the linear gradient has only 0 deg transform (which is default).

- Add input in the color picker modal to take angle as user input.
- Transform gradient according to the angle.
- gradientTransform should be the key to solve this

Ex- 
```defs>
    <linearGradient id="myGradient" gradientTransform="rotate(90)">
      <stop offset="5%"  stop-color="gold" />
      <stop offset="95%" stop-color="red" />
    </linearGradient>
```

**Comment by TaneliR** [comment]
I could try to add this functionality 👍

**Comment by anup-a** [comment]
@TaneliR  Yeah sure thanks. Assigning this to you. Feel free to ask questions if something isn't clear to you.
