### ISSUE TITLE
[React] Change bgcolor of color picker when theme changes ( dark/light)

### ISSUE THREAD

**Issue by anup-a** [anup-a/svgwave#4]
- As of now rest of the components follow the dark/light theme mode.
- However, the background color of color picker ( twittercolorpicker from react-color) persists to white.
- Task is to change it to some shade of black when theme changes dark mode.

PS: Twitter color picker seems to take styles as prop, but inlinestyles doesn't seems to work.

**Comment by LeaFranz** [comment]
I'd love to help, but where do I find the contribution guide?

**Comment by anup-a** [comment]
@LeaFranz project is at a very nascent stage ... I might need some time to add contribution guide.

You can follow standard guidelines -
- Fork the repo
- `yarn start` or `npm start` to run project in dev mode
- Make your changes
- Create a pull request

Feel free to ask any doubts.

PS - Try not uses which might degrade performance.

**Comment by LeaFranz** [comment]
@anup-a Thanks! Could you assign this to me?
