### ISSUE TITLE
[React] Add loading animation to svgwave.in

### ISSUE THREAD

**Issue by anup-a** [anup-a/svgwave#5]
As of now there is no loading animation till page fully renders.

Task is simple - 

- discuss/suggest the loading animation in thread ( theme compatible )
- implement a loader in react app

Helpful links  - [loading.io](https://www.loading.io)

PS -try not to use any third-party libraries.

**Comment by ansh-saini** [comment]
Can I work on this?

**Comment by anup-a** [comment]
Go ahead

**Comment by anup-a** [comment]
Note : stick to simple svgs or css for assets

**Comment by ansh-saini** [comment]
https://codepen.io/FauxyCoder/full/LYYmKJG
Is something like this okay?

I can tweak the colors and size

**Comment by anup-a** [comment]
Yup. looks elegant. you can change color to default svgwave.in has

**Comment by ansh-saini** [comment]
Alright. I'm also thinking of remove the box shadow. Since the actual loader would have a small size.
100x100 maybe?
Or is the 400x400 size okay?

**Comment by anup-a** [comment]
100X100 would be better. Actually my initial thoughts were to animate the logo itself. 

If you are very well verse with css animation you could try that to . (I can provide assets)
Or else you could continue with this one https://codepen.io/FauxyCoder/full/LYYmKJG

**Comment by ansh-saini** [comment]
I'm not that great with CSS Animations tbh.
I think I'll proceed with the codepen one.

**Comment by ansh-saini** [comment]
Hey! I got caught up with some stuff. I've implemented the loader in the app. Just need to cleanup some code. I'll submit the PR tomorrow.
