### ISSUE TITLE
SVGwave background

### ISSUE THREAD

**Issue by Vortexxx10** [anup-a/svgwave#69]
C'est pour le image svg

**Comment by anup-a** [comment]
Hi @Vortexxx10 , Can you translate your message in English?

**Comment by Vortexxx10** [comment]
> Hi @Vortexxx10 , Can you translate your message in English?

It 's for svg

**Comment by Vortexxx10** [comment]
> Hi @Vortexxx10 , Can you translate your message in English?

It's for svg image
