### ISSUE TITLE
Add twitter share widget [React]

### ISSUE THREAD

**Issue by anup-a** [anup-a/svgwave#76]
- Replace the broken twitter icon with twitter share widget
- Reference and Example - https://developer.twitter.com/en/docs/twitter-for-websites/tweet-button/overview
<img width="732" alt="Screenshot 2022-10-04 at 10 33 53 AM" src="https://user-images.githubusercontent.com/29516633/193738484-6f61210e-9edb-45f5-82f5-77359778f0a7.png">

**Comment by jason1985** [comment]
I'd like to give this one a shot.

**Comment by jason1985** [comment]
@anup-a just to make sure I understand the issue correctly.
Is this functionality correct?

![demo](https://user-images.githubusercontent.com/10107412/193743228-708db338-0fcf-4895-b92c-0f04d1b0bd1a.gif)

**Comment by anup-a** [comment]
@jason1985 Yes precisely. 

Quick question - Is the tool not working correctly in the Brave browser, or your screen recorder is causing a rendering issue?

**Comment by jason1985** [comment]
@anup-a I don't know any cool phrases to put 😅. 
It seems to be working well in Brave, I think it's just the screen recorder tool.

**Comment by anup-a** [comment]
okay, I will figure it out later 😅. Lets keep it simple "Try this cool website to generate svg waves".

**Comment by anup-a** [comment]
Merged! 

Thank you @jason1985
