### ISSUE TITLE
[React] Add dark mode to web component 

### ISSUE THREAD

**Issue by anup-a** [anup-a/svgwave#81]
<img width="1439" alt="Screenshot 2022-10-26 at 8 55 21 PM" src="https://user-images.githubusercontent.com/29516633/198077735-b420007a-55bd-49ff-9e17-271c21fe0bb9.png">

Since the `float-menu` popover is a web component, this is not straightforward.

So the approach should be to pass `isDark` var to `float-menu`, and conditionally have dark mode styles

Follow the reference article - [`Medium`](https://medium.com/technofunnel/creating-passing-data-to-html-custom-elements-using-attributes-bfd9aa759fd4)

**Comment by simonpankovski** [comment]
Hey, I would like to work on this issue.

**Comment by anup-a** [comment]
That's great. Assigned to you.
