### ISSUE TITLE
suggetion: Add option to edit svg direction in free-direction

### ISSUE THREAD

**Issue by MustkimKhatik** [anup-a/svgwave#84]
currently there is only two SVG direction option which is only horizontal, maybe we can add the option to rotate the svg in every direction for e.g. SVG starting from left bottom corner until right upper corner.

**Comment by anup-a** [comment]
@MustkimKhatik Sorry for the late response.
Yes it actually sounds good and I'm currently redesigning so would be a good feature to add.

**Comment by anup-a** [comment]
@MustkimKhatik 
I did add a similar feature - "Wave modes", not very flexible but could be helpful. [Visit Preview](https://svgwave-git-wave-direction-anup-a.vercel.app/)
