### ISSUE TITLE
Will Google-Analytics info be freely available?

### ISSUE THREAD

**Issue by r-i-c-h** [anup-a/svgwave#9]
Saw https://github.com/anup-a/svgwave/commit/00b68bd1f99d22eb552168ac51b05d68459103b3 - Am wondering what you will do with said analytics data? Will it be freely available?

**Comment by anup-a** [comment]
Isn't it visible for every website in the page source code anyway? I'm not very sure.

I think unless someone wants to plug my tracking Id just to mess with data reflected in the google analytics, it is fine.

**Comment by anup-a** [comment]
> Am wondering what you will do with said analytics data?

-> The whole mini-project was for me to try out few things.
This is the first time I was using -

- Webpack
- Postcss
- Tailwind
- Preact
- SVGs path ( bezier curves)
- Google analytics ( answers your question ... I'll remove it after sometime )
